apiVersion: v2
appVersion: 1.0.2
description: Chart holding app-exporter.
home: https://github.com/giantswarm/app-exporter
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
name: app-exporter
version: 1.0.2
annotations:
  io.giantswarm.application.team: honeybadger
